variable "general_config" {
  type = map(any)
}
variable "regions" {
  type = map(any)
}
variable "vpc_cidr" {}
variable "availability_zones" {}
variable "public_subnets" {}
variable "dmz_subnets" {}
variable "private_subnets" {}
variable "ami" {}
variable "instance_type_web" {}
variable "volume_type_web" {}
variable "volume_size_web" {}
variable "key_name_web" {}
variable "public_key_path_web" {}
variable "instance_type_bastion" {}
variable "volume_type_bastion" {}
variable "volume_size_bastion" {}
variable "key_name_bastion" {}
variable "public_key_path_bastion" {}
variable "public_subnet_ids" {}
variable "dmz_subnet_ids" {}
variable "private_subnet_ids" {}
variable "instance_ids" {}
#variable "zone_name" {}
variable "sub_domain_1" {}
variable "sub_domain_2" {}
variable "engine_name" {}
variable "major_engine_version" {}
variable "engine" {}
variable "engine_version" {}
variable "username" {}
variable "password" {}
variable "instance_class" {}
variable "storage_type" {}
variable "allocated_storage" {}
variable "multi_az" {}
variable "sns_email" {}
variable "cwa_actions" {}
variable "cwa_threshold_rds_freeablememory" {}
variable "cwa_threshold_rds_freeablestorage" {}
provider "aws" {
  alias  = "us-east-1"
  region = var.regions["virginia"]
}